version: '3.8'

services:
  #1. Container: RabbitMQ (Veri Kuyruğu - Container C)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: interpol-rabbit
    ports:
      - "5672:5672" #Kodların İletişim Portu
      - "15672:15672" #Yönetim paneli portu
    healthcheck: #RabbitMQ tam açılmadan diğerlerini başlatma
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  #2. Container: Producer (Veri Çeken - Container A)
  producer:
    build: ./producer
    container_name: interpol-producer
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbitmq
      - QUEUE_NAME=interpol_queue
      - SLEEP_TIME=86400 #24 SAATTE BİR ÇALIŞ
      - API_URL=https://ws-public.interpol.int/notices/v1/red?resultPerPage=160&page=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    # RabbitMQ hazır olana kadar bekle
    restart: always

  #3. Container: Web/Consumer (Arayüz - Container B)
  web:
    build: ./web
    container_name: interpol-web
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbitmq
      - QUEUE_NAME=interpol_queue
      - DB_NAME=interpol.db
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - SECRET_KEY=f0f1598b3fd3fc29a8dab0cb6a9ae29205369b364b4c94bd
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
    - ./web:/app

  #4. Container: Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: interpol_user
      POSTGRES_PASSWORD: gizlisifre123
      POSTGRES_DB: interpol_db
    ports:
      - "5432:5432"  # Dışarıdan erişim için (Opsiyonel)
    volumes:
      # [VOLUME_ADI] : [KONTEYNER_İÇİNDEKİ_HEDEF_KLASÖR]
      - postgres_data:/var/lib/postgresql/data
    restart: always

# 5. MinIO (Resim Deposu - AWS S3 Alternatifi)
  minio:
    image: minio/minio
    container_name: interpol_minio
    ports:
      - "9000:9000"  # API Portu (Python kodu buraya bağlanır)
      - "9001:9001"  # Arayüz Portu (Tarayıcıdan sen girersin)
    environment:
      MINIO_ROOT_USER: minioadmin     # app.py'deki KEY ile aynı olmalı
      MINIO_ROOT_PASSWORD: minioadmin # app.py'deki SECRET ile aynı olmalı
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
  web:


